# Generated by Django 4.0.5 on 2024-07-03 17:51

from django.db import migrations, models
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='DELHI', max_length=2),
        ),
    ]
