# Generated by Django 4.0.5 on 2024-07-04 10:14

from django.db import migrations
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='Delhi', max_length=2),
        ),
    ]
