# Generated by Django 4.0.5 on 2024-07-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_location_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
