# Generated by Django 4.2.13 on 2024-07-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='brand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='color',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='vin',
            new_name='Engine_no',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='mileage',
            new_name='Mileage',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='model',
            new_name='Model',
        ),
    ]
