# Generated by Django 4.2.13 on 2024-10-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_listing_brand_likedlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedlisting',
            old_name='liked_date',
            new_name='like_date',
        ),
    ]
